spring.data.mongodb.uri=mongodb://localhost:27017/airline_db

# JWT configuration (unchanged)
airline.app.jwtSecret=skyluxSecretKey2026ForAirlineSystemDevelopmentPurposeOnlyMustBeVeryLongToSatisfyHS512SecurityRequirements
airline.app.jwtAccessTokenExpirationMs=86400000
airline.app.jwtRefreshTokenExpirationMs=86400000

# Logging
logging.level.org.springframework.security=INFO
logging.level.com.airline=INFO
logging.level.org.hibernate.SQL=INFO

# Cloudinary
cloudinary.cloud-name=dgnvtrxct
cloudinary.api-key=286467827619326
cloudinary.api-secret=3MrqU2AIP8Y4b7W6_R22TR8L2WQ
