server.port=${PORT:8080}
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/airline_db}

# JWT configuration
airline.app.jwtSecret=${JWT_SECRET:skyluxSecretKey2026ForAirlineSystemDevelopmentPurposeOnlyMustBeVeryLongToSatisfyHS512SecurityRequirements}
airline.app.jwtAccessTokenExpirationMs=86400000
airline.app.jwtRefreshTokenExpirationMs=86400000

# CORS Support
airline.app.frontendUrl=${FRONTEND_URL:http://localhost:5173}

# Logging
logging.level.org.springframework.security=INFO
logging.level.com.airline=INFO
logging.level.org.hibernate.SQL=INFO

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dgnvtrxct}
cloudinary.api-key=${CLOUDINARY_API_KEY:286467827619326}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:3MrqU2AIP8Y4b7W6_R22TR8L2WQ}
